### ISSUE TITLE
ValueError: need at least one array to stack

### ISSUE THREAD

**Issue by nene11** [SuperBruceJia/EEG-Motor-Imagery-Classification-CNNs-TensorFlow#1]
hi
i try to run your code but it give me this error  :ValueError: need at least one array to stack and i am sure the path is the correct path for the data set can you help me

**Comment by SuperBruceJia** [comment]
Hey bro, sorry for my delayed response.
Which file's codes give you the error? Do u use "Read_Raw_Data_Save_Into_Matlab_Files.py"? Please be sure to execute it under Python 2 environment. Or you could tell me the file and the lines. Thanks bro.

**Comment by SuperBruceJia** [comment]
My apologies, bro, one thing you should know is that the official website of Motor Imagery Dataset has changed to https://archive.physionet.org/pn4/eegmmidb/. So you should use this website in the "MIND_Get_EDF.py" file. I have changed the path in the file so that you could download the dataset.
