### ISSUE TITLE
need the lead field matrix and scout indices

### ISSUE THREAD

**Issue by Mrswolf** [SuperBruceJia/EEG-Motor-Imagery-Classification-CNNs-TensorFlow#2]
Hi

I am reading the paper now.

Can you provide the lead field matrix and scout indices used in the paper? That would be helpful. I think they could be exported from the Brainstorm.

Thank you.

**Comment by SuperBruceJia** [comment]
Hi,

Sorry for the late response. I wish I could help you. Unfortunately, my job in this work was to design a CNN architecture, and my senior sister, a postgraduate student in NEEPU, did the pre-processing work. All I knew was that she used the MATLAB Brainstorm software (toolkit) to process the raw data. Thus, my advice was that you can try to use the Brainstorm to reproduce the results.

Best,

Shuyue
