### ISSUE TITLE
Data processing before entering CNN

### ISSUE THREAD

**Issue by zhouyanghuang1** [SuperBruceJia/EEG-Motor-Imagery-Classification-CNNs-TensorFlow#5]
Hello, I would like to ask if you split the 23-by-640 time-frequency diagram obtained after the combined time-frequency analysis into 23 32-by-20 recompositions and put them into CNN?

**Comment by SuperBruceJia** [comment]
Yep. The `23 X 640` matrix has been processed as 23 `32 X 20` matrixes. 
The reasons why we are doing it:
1. Dataset Extension, i.e., we can have many more data, which is essential to Deep Learning-based methods, e.g., CNNs.
2. A novel way to process the signals. In detail, first of all, we processed the temporal signals into time-frequency maps, i.e., the `time X frequency` matrixes. Then, we decomposed them as `time X single-frequency` matrixes. Last but not least, a CNN architecture was proposed to decode the EEG tasks.
3. The results outperform that regarding the `23 X 640` matrix based on CNN models.

If u have additional questions, let me know.

Best,

Shuyue

**Comment by zhouyanghuang1** [comment]
Thank you very much for taking time out of your busy schedule to dispel doubts!

There's one more thing I don't know:
The time-frequency diagram obtained after combined time-frequency analysis is of the order of magnitude around 10E-22, but the order of magnitude of the single-frequency matrix is around 10E0. I want to know how does this step actually translate?

Thank you

**Comment by SuperBruceJia** [comment]
> Thank you very much for taking time out of your busy schedule to dispel doubts!
> 
> There's one more thing I don't know:
> The time-frequency diagram obtained after combined time-frequency analysis is of the order of magnitude around 10E-22, but the order of magnitude of the single-frequency matrix is around 10E0. I want to know how does this step actually translate?
> 
> Thank you

Hi,

You should double-check the codes, especially the [pre-processing](https://github.com/SuperBruceJia/EEG-Motor-Imagery-Classification-CNNs-TensorFlow/blob/master/Saved_Matlab_Data/Preprocessing_Raw_Data.m) one from line 81 to 86 as an example. After we got the time-frequency maps, we normalized the singles in order to better train the Deep Neural Networks. The reason why we normalized

**Comment by maqsood-shah-uncc** [comment]
I tried many times in python 2.7, but overtime it gves the following error.

return np.array(trials, dtype=np.float64).reshape((len(trials),) + trials[0].shape + (1,)), np.array(labels, dtype=np.float64)
IndexError: list index out of range
